import oracledb from 'oracledb';
import { config } from '../config.js';

oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;
oracledb.fetchAsString = [oracledb.CLOB];

let poolInitialized = false;

function toClobBind(value) {
  return {
    val: value,
    type: oracledb.CLOB
  };
}

function toVectorJson(embedding) {
  return JSON.stringify(embedding);
}

async function withConnection(callback) {
  const connection = await oracledb.getConnection();

  try {
    return await callback(connection);
  } finally {
    await connection.close();
  }
}

async function createObjectIfMissing(connection, ddl) {
  const wrappedDdl = `
    BEGIN
      EXECUTE IMMEDIATE q'~${ddl}~';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;`;

  await connection.execute(wrappedDdl);
}

async function addColumnIfMissing(connection, tableName, columnName, columnDdl) {
  const result = await connection.execute(
    `SELECT COUNT(*) AS column_count
       FROM user_tab_columns
      WHERE table_name = UPPER(:table_name)
        AND column_name = UPPER(:column_name)`,
    {
      table_name: tableName,
      column_name: columnName
    }
  );

  if (Number(result.rows[0]?.COLUMN_COUNT || 0) > 0) {
    return;
  }

  await connection.execute(`ALTER TABLE ${tableName} ADD (${columnDdl})`);
}

async function ensureSchema() {
  await withConnection(async (connection) => {
    await createObjectIfMissing(
      connection,
      `CREATE TABLE documents (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        original_name VARCHAR2(1024) NOT NULL,
        stored_name VARCHAR2(1024) NOT NULL,
        storage_path VARCHAR2(2048) NOT NULL,
        mime_type VARCHAR2(255),
        file_size NUMBER,
        status VARCHAR2(30) DEFAULT 'processing' NOT NULL,
        chunk_count NUMBER DEFAULT 0 NOT NULL,
        error_message VARCHAR2(4000),
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      )`
    );

    await addColumnIfMissing(
      connection,
      'documents',
      'document_store_provider',
      'document_store_provider VARCHAR2(50)'
    );

    await addColumnIfMissing(
      connection,
      'documents',
      'oci_file_id',
      'oci_file_id VARCHAR2(255)'
    );

    await addColumnIfMissing(
      connection,
      'documents',
      'oci_vector_store_file_id',
      'oci_vector_store_file_id VARCHAR2(255)'
    );

    await addColumnIfMissing(
      connection,
      'documents',
      'summary_text',
      'summary_text CLOB'
    );

    await addColumnIfMissing(
      connection,
      'documents',
      'short_description',
      'short_description VARCHAR2(512)'
    );

    await createObjectIfMissing(
      connection,
      `CREATE TABLE document_chunks (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        document_id NUMBER NOT NULL,
        chunk_index NUMBER NOT NULL,
        chunk_text CLOB NOT NULL,
        embedding VECTOR(${config.rag.embeddingDimension}, FLOAT32) NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_document_chunks_document
          FOREIGN KEY (document_id)
          REFERENCES documents(id)
          ON DELETE CASCADE
      )`
    );

    await createObjectIfMissing(
      connection,
      'CREATE INDEX idx_document_chunks_document ON document_chunks (document_id, chunk_index)'
    );

    await createObjectIfMissing(
      connection,
      `CREATE TABLE templates (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        original_name VARCHAR2(1024) NOT NULL,
        stored_name VARCHAR2(1024) NOT NULL,
        storage_path VARCHAR2(2048) NOT NULL,
        mime_type VARCHAR2(255),
        file_size NUMBER,
        template_text CLOB NOT NULL,
        rules_json CLOB NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      )`
    );

    await addColumnIfMissing(
      connection,
      'templates',
      'document_store_provider',
      'document_store_provider VARCHAR2(50)'
    );

    await addColumnIfMissing(
      connection,
      'templates',
      'oci_file_id',
      'oci_file_id VARCHAR2(255)'
    );

    await addColumnIfMissing(
      connection,
      'templates',
      'oci_vector_store_file_id',
      'oci_vector_store_file_id VARCHAR2(255)'
    );

    await createObjectIfMissing(
      connection,
      `CREATE TABLE template_chunks (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        template_id NUMBER NOT NULL,
        chunk_index NUMBER NOT NULL,
        chunk_text CLOB NOT NULL,
        embedding VECTOR(${config.rag.embeddingDimension}, FLOAT32) NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_template_chunks_template
          FOREIGN KEY (template_id)
          REFERENCES templates(id)
          ON DELETE CASCADE
      )`
    );

    await createObjectIfMissing(
      connection,
      'CREATE INDEX idx_template_chunks_template ON template_chunks (template_id, chunk_index)'
    );

    await createObjectIfMissing(
      connection,
      `CREATE TABLE validation_results (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        template_id NUMBER NOT NULL,
        document_name VARCHAR2(1024) NOT NULL,
        result_json CLOB NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_validation_results_template
          FOREIGN KEY (template_id)
          REFERENCES templates(id)
          ON DELETE CASCADE
      )`
    );

    await addColumnIfMissing(
      connection,
      'validation_results',
      'document_store_provider',
      'document_store_provider VARCHAR2(50)'
    );

    await addColumnIfMissing(
      connection,
      'validation_results',
      'oci_file_id',
      'oci_file_id VARCHAR2(255)'
    );

    await addColumnIfMissing(
      connection,
      'validation_results',
      'oci_vector_store_file_id',
      'oci_vector_store_file_id VARCHAR2(255)'
    );

    await createObjectIfMissing(
      connection,
      `CREATE TABLE validation_result_chunks (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        validation_result_id NUMBER NOT NULL,
        chunk_index NUMBER NOT NULL,
        chunk_text CLOB NOT NULL,
        embedding VECTOR(${config.rag.embeddingDimension}, FLOAT32) NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_validation_chunks_result
          FOREIGN KEY (validation_result_id)
          REFERENCES validation_results(id)
          ON DELETE CASCADE
      )`
    );

    await createObjectIfMissing(
      connection,
      'CREATE INDEX idx_validation_chunks_result ON validation_result_chunks (validation_result_id, chunk_index)'
    );

    await createObjectIfMissing(
      connection,
      'CREATE INDEX idx_validation_results_template ON validation_results (template_id)'
    );
  });
}

export async function initializeOracle() {
  if (poolInitialized) {
    return;
  }

  await oracledb.createPool({
    user: config.oracle.user,
    password: config.oracle.password,
    connectString: config.oracle.connectString,
    poolMin: config.oracle.poolMin,
    poolMax: config.oracle.poolMax,
    poolIncrement: config.oracle.poolIncrement
  });

  poolInitialized = true;
  await ensureSchema();
}

export async function closeOracle() {
  if (!poolInitialized) {
    return;
  }

  const pool = oracledb.getPool();
  await pool.close(0);
  poolInitialized = false;
}

export async function createDocument(file) {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `INSERT INTO documents (
        original_name,
        stored_name,
        storage_path,
        mime_type,
        file_size,
        document_store_provider,
        status
      ) VALUES (
        :original_name,
        :stored_name,
        :storage_path,
        :mime_type,
        :file_size,
        :document_store_provider,
        'processing'
      ) RETURNING id INTO :id`,
      {
        original_name: file.originalName,
        stored_name: file.storedName,
        storage_path: file.storagePath,
        mime_type: file.mimeType,
        file_size: file.fileSize,
        document_store_provider: file.documentStoreProvider || null,
        id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
      }
    );

    await connection.commit();
    return result.outBinds.id[0];
  });
}

export async function updateDocumentStatus(documentId, status, options = {}) {
  const {
    chunkCount = null,
    errorMessage = null,
    summaryText = null,
    shortDescription = null
  } = options;

  await withConnection(async (connection) => {
    const assignments = ['status = :status', 'error_message = :error_message'];
    const binds = {
      status,
      error_message: {
        val: errorMessage,
        type: oracledb.STRING,
        maxSize: 4000
      },
      id: {
        val: documentId,
        type: oracledb.NUMBER
      }
    };

    if (chunkCount !== null) {
      assignments.push('chunk_count = :chunk_count');
      binds.chunk_count = {
        val: chunkCount,
        type: oracledb.NUMBER
      };
    }

    if (summaryText !== null) {
      assignments.push('summary_text = :summary_text');
      binds.summary_text = toClobBind(summaryText);
    }

    if (shortDescription !== null) {
      assignments.push('short_description = :short_description');
      binds.short_description = {
        val: shortDescription,
        type: oracledb.STRING,
        maxSize: 512
      };
    }

    await connection.execute(
      `UPDATE documents
         SET ${assignments.join(', ')}
       WHERE id = :id`,
      binds
    );

    await connection.commit();
  });
}

export async function updateDocumentOciMetadata(documentId, metadata = {}) {
  await withConnection(async (connection) => {
    await connection.execute(
      `UPDATE documents
          SET oci_file_id = :oci_file_id,
              oci_vector_store_file_id = :oci_vector_store_file_id,
              document_store_provider = :document_store_provider
        WHERE id = :id`,
      {
        oci_file_id: metadata.ociFileId || null,
        oci_vector_store_file_id: metadata.ociVectorStoreFileId || null,
        document_store_provider: metadata.documentStoreProvider || 'oci-vector-store',
        id: {
          val: documentId,
          type: oracledb.NUMBER
        }
      }
    );

    await connection.commit();
  });
}

export async function replaceDocumentChunks(documentId, chunks, embeddings) {
  await withConnection(async (connection) => {
    await connection.execute(
      'DELETE FROM document_chunks WHERE document_id = :document_id',
      {
        document_id: {
          val: Number(documentId),
          type: oracledb.NUMBER
        }
      }
    );

    for (const chunk of chunks) {
      const embedding = embeddings[chunk.index];
      await connection.execute(
        `INSERT INTO document_chunks (
          document_id,
          chunk_index,
          chunk_text,
          embedding
        ) VALUES (
          :document_id,
          :chunk_index,
          :chunk_text,
          TO_VECTOR(:embedding_json)
        )`,
        {
          document_id: {
            val: Number(documentId),
            type: oracledb.NUMBER
          },
          chunk_index: {
            val: chunk.index,
            type: oracledb.NUMBER
          },
          chunk_text: toClobBind(chunk.text),
          embedding_json: toClobBind(toVectorJson(embedding))
        }
      );
    }

    await connection.commit();
  });
}

export async function deleteDocumentChunks(documentId) {
  await withConnection(async (connection) => {
    await connection.execute(
      'DELETE FROM document_chunks WHERE document_id = :document_id',
      {
        document_id: {
          val: Number(documentId),
          type: oracledb.NUMBER
        }
      }
    );

    await connection.commit();
  });
}

export async function updateDocumentForReupload(documentId, file) {
  await withConnection(async (connection) => {
    await connection.execute(
      `UPDATE documents
          SET stored_name = :stored_name,
              storage_path = :storage_path,
              mime_type = :mime_type,
              file_size = :file_size,
              status = 'processing',
              chunk_count = 0,
              error_message = NULL,
              summary_text = NULL,
              short_description = NULL,
              document_store_provider = :document_store_provider
        WHERE id = :id`,
      {
        stored_name: file.storedName,
        storage_path: file.storagePath,
        mime_type: file.mimeType,
        file_size: file.fileSize,
        document_store_provider: file.documentStoreProvider || null,
        id: {
          val: documentId,
          type: oracledb.NUMBER
        }
      }
    );

    await connection.commit();
  });
}

export async function listDocuments() {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `SELECT
         id,
         original_name,
         stored_name,
         storage_path,
         mime_type,
         file_size,
         status,
         chunk_count,
         document_store_provider,
         oci_file_id,
         oci_vector_store_file_id,
         summary_text,
         short_description,
         error_message,
         created_at
       FROM documents
       ORDER BY created_at DESC`
    );

    return result.rows;
  });
}

export async function findDocumentByOriginalName(originalName) {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `SELECT
         id,
         original_name,
         stored_name,
         storage_path,
         mime_type,
         file_size,
         status,
         chunk_count,
         summary_text,
         short_description,
         error_message,
         created_at
       FROM documents
      WHERE original_name = :original_name
      ORDER BY created_at DESC
      FETCH FIRST 1 ROWS ONLY`,
      {
        original_name: originalName
      }
    );

    return result.rows[0] || null;
  });
}

export async function findDocumentById(documentId) {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `SELECT
         id,
         original_name,
         stored_name,
         storage_path,
         mime_type,
         file_size,
         status,
         chunk_count,
         summary_text,
         short_description,
         error_message,
         created_at
       FROM documents
      WHERE id = :document_id`,
      {
        document_id: documentId
      }
    );

    return result.rows[0] || null;
  });
}

export async function listDocumentChunksById(documentId, limit = 10) {
  const safeLimit = Math.max(1, Math.min(Number(limit) || 10, 40));

  return withConnection(async (connection) => {
    const result = await connection.execute(
      `SELECT
         dc.chunk_text,
         dc.chunk_index,
         d.original_name
       FROM document_chunks dc
       JOIN documents d ON d.id = dc.document_id
      WHERE d.id = :document_id
        AND d.status = 'ready'
      ORDER BY dc.chunk_index
      FETCH FIRST ${safeLimit} ROWS ONLY`,
      {
        document_id: documentId
      }
    );

    return result.rows.map((row) => ({
      text: row.CHUNK_TEXT,
      chunkIndex: row.CHUNK_INDEX,
      originalName: row.ORIGINAL_NAME
    }));
  });
}

export async function searchSimilarChunks(queryEmbedding, topK) {
  const safeTopK = Math.max(1, Math.min(Number(topK) || config.rag.topK, 20));

  return withConnection(async (connection) => {
    const result = await connection.execute(
      `SELECT
         dc.id,
         dc.document_id,
         dc.chunk_index,
         dc.chunk_text,
         d.original_name,
         d.storage_path,
         VECTOR_DISTANCE(dc.embedding, TO_VECTOR(:embedding_json), COSINE) AS distance
       FROM document_chunks dc
       JOIN documents d ON d.id = dc.document_id
      WHERE d.status = 'ready'
        AND NVL(d.document_store_provider, 'oci-vector-store') = 'oracle-db'
      ORDER BY distance ASC
      FETCH FIRST ${safeTopK} ROWS ONLY`,
      {
        embedding_json: toClobBind(toVectorJson(queryEmbedding))
      }
    );

    return result.rows.map((row) => ({
      id: row.ID,
      documentId: row.DOCUMENT_ID,
      chunkIndex: row.CHUNK_INDEX,
      text: row.CHUNK_TEXT,
      originalName: row.ORIGINAL_NAME,
      storagePath: row.STORAGE_PATH,
      distance: row.DISTANCE,
      score: typeof row.DISTANCE === 'number' ? Math.max(0, 1 - row.DISTANCE) : null
    }));
  });
}

export async function searchSimilarChunksForDocument(documentId, queryEmbedding, topK) {
  const safeTopK = Math.max(1, Math.min(Number(topK) || config.rag.topK, 20));

  return withConnection(async (connection) => {
    const result = await connection.execute(
      `SELECT
         dc.id,
         dc.document_id,
         dc.chunk_index,
         dc.chunk_text,
         d.original_name,
         d.storage_path,
         VECTOR_DISTANCE(dc.embedding, TO_VECTOR(:embedding_json), COSINE) AS distance
       FROM document_chunks dc
       JOIN documents d ON d.id = dc.document_id
      WHERE d.status = 'ready'
        AND d.id = :document_id
        AND NVL(d.document_store_provider, 'oci-vector-store') = 'oracle-db'
      ORDER BY distance ASC
      FETCH FIRST ${safeTopK} ROWS ONLY`,
      {
        document_id: documentId,
        embedding_json: toClobBind(toVectorJson(queryEmbedding))
      }
    );

    return result.rows.map((row) => ({
      id: row.ID,
      documentId: row.DOCUMENT_ID,
      chunkIndex: row.CHUNK_INDEX,
      text: row.CHUNK_TEXT,
      originalName: row.ORIGINAL_NAME,
      storagePath: row.STORAGE_PATH,
      distance: row.DISTANCE,
      score: typeof row.DISTANCE === 'number' ? Math.max(0, 1 - row.DISTANCE) : null
    }));
  });
}

export async function createTemplate(template) {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `INSERT INTO templates (
        original_name,
        stored_name,
        storage_path,
        mime_type,
        file_size,
        template_text,
        rules_json,
        document_store_provider,
        oci_file_id,
        oci_vector_store_file_id
      ) VALUES (
        :original_name,
        :stored_name,
        :storage_path,
        :mime_type,
        :file_size,
        :template_text,
        :rules_json,
        :document_store_provider,
        :oci_file_id,
        :oci_vector_store_file_id
      ) RETURNING id INTO :id`,
      {
        original_name: template.originalName,
        stored_name: template.storedName,
        storage_path: template.storagePath,
        mime_type: template.mimeType,
        file_size: template.fileSize,
        template_text: toClobBind(template.templateText),
        rules_json: toClobBind(template.rulesJson),
        document_store_provider: template.documentStoreProvider || null,
        oci_file_id: template.ociFileId || null,
        oci_vector_store_file_id: template.ociVectorStoreFileId || null,
        id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
      }
    );

    await connection.commit();
    return result.outBinds.id[0];
  });
}

export async function listTemplates() {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `SELECT
         id,
         original_name,
         stored_name,
         storage_path,
         mime_type,
         file_size,
         rules_json,
         document_store_provider,
         oci_file_id,
         oci_vector_store_file_id,
         created_at
       FROM templates
       ORDER BY created_at DESC`
    );

    return result.rows;
  });
}

export async function getTemplate(templateId) {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `SELECT
         id,
         original_name,
         stored_name,
         storage_path,
         mime_type,
         file_size,
         template_text,
         rules_json,
         document_store_provider,
         oci_file_id,
         oci_vector_store_file_id,
         created_at
       FROM templates
       WHERE id = :id`,
      {
        id: {
          val: Number(templateId),
          type: oracledb.NUMBER
        }
      }
    );

    return result.rows[0] || null;
  });
}

export async function createValidationResult(validationResult) {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `INSERT INTO validation_results (
        template_id,
        document_name,
        result_json,
        document_store_provider,
        oci_file_id,
        oci_vector_store_file_id
      ) VALUES (
        :template_id,
        :document_name,
        :result_json,
        :document_store_provider,
        :oci_file_id,
        :oci_vector_store_file_id
      ) RETURNING id INTO :id`,
      {
        template_id: {
          val: Number(validationResult.templateId),
          type: oracledb.NUMBER
        },
        document_name: validationResult.documentName,
        result_json: toClobBind(validationResult.resultJson),
        document_store_provider: validationResult.documentStoreProvider || null,
        oci_file_id: validationResult.ociFileId || null,
        oci_vector_store_file_id: validationResult.ociVectorStoreFileId || null,
        id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
      }
    );

    await connection.commit();
    return result.outBinds.id[0];
  });
}

export async function replaceTemplateChunks(templateId, chunks, embeddings) {
  await withConnection(async (connection) => {
    await connection.execute(
      'DELETE FROM template_chunks WHERE template_id = :template_id',
      {
        template_id: {
          val: Number(templateId),
          type: oracledb.NUMBER
        }
      }
    );

    for (const chunk of chunks) {
      await connection.execute(
        `INSERT INTO template_chunks (
          template_id,
          chunk_index,
          chunk_text,
          embedding
        ) VALUES (
          :template_id,
          :chunk_index,
          :chunk_text,
          TO_VECTOR(:embedding_json)
        )`,
        {
          template_id: {
            val: Number(templateId),
            type: oracledb.NUMBER
          },
          chunk_index: {
            val: chunk.index,
            type: oracledb.NUMBER
          },
          chunk_text: toClobBind(chunk.text),
          embedding_json: toClobBind(toVectorJson(embeddings[chunk.index]))
        }
      );
    }

    await connection.commit();
  });
}

export async function replaceValidationResultChunks(validationResultId, chunks, embeddings) {
  await withConnection(async (connection) => {
    await connection.execute(
      'DELETE FROM validation_result_chunks WHERE validation_result_id = :validation_result_id',
      {
        validation_result_id: {
          val: Number(validationResultId),
          type: oracledb.NUMBER
        }
      }
    );

    for (const chunk of chunks) {
      await connection.execute(
        `INSERT INTO validation_result_chunks (
          validation_result_id,
          chunk_index,
          chunk_text,
          embedding
        ) VALUES (
          :validation_result_id,
          :chunk_index,
          :chunk_text,
          TO_VECTOR(:embedding_json)
        )`,
        {
          validation_result_id: {
            val: Number(validationResultId),
            type: oracledb.NUMBER
          },
          chunk_index: {
            val: chunk.index,
            type: oracledb.NUMBER
          },
          chunk_text: toClobBind(chunk.text),
          embedding_json: toClobBind(toVectorJson(embeddings[chunk.index]))
        }
      );
    }

    await connection.commit();
  });
}
