import oracledb from 'oracledb';
import { config } from '../config.js';

oracledb.outFormat = oracledb.OUT_FORMAT_OBJECT;
oracledb.fetchAsString = [oracledb.CLOB];

let poolInitialized = false;

function toVectorJson(embedding) {
  if (!Array.isArray(embedding)) {
    throw new Error('Embedding must be an array.');
  }

  if (embedding.length !== config.rag.embeddingDimension) {
    throw new Error(
      `Embedding dimension mismatch. Expected ${config.rag.embeddingDimension}, received ${embedding.length}.`
    );
  }

  return JSON.stringify(embedding);
}

function toClobBind(value) {
  return {
    val: value,
    type: oracledb.CLOB
  };
}

async function withConnection(callback) {
  const connection = await oracledb.getConnection();

  try {
    return await callback(connection);
  } finally {
    await connection.close();
  }
}

async function createObjectIfMissing(connection, ddl) {
  const wrappedDdl = `
    BEGIN
      EXECUTE IMMEDIATE q'~${ddl}~';
    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
          RAISE;
        END IF;
    END;`;

  await connection.execute(wrappedDdl);
}

async function ensureSchema() {
  await withConnection(async (connection) => {
    await createObjectIfMissing(
      connection,
      `CREATE TABLE documents (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        original_name VARCHAR2(1024) NOT NULL,
        stored_name VARCHAR2(1024) NOT NULL,
        storage_path VARCHAR2(2048) NOT NULL,
        mime_type VARCHAR2(255),
        file_size NUMBER,
        status VARCHAR2(30) DEFAULT 'processing' NOT NULL,
        chunk_count NUMBER DEFAULT 0 NOT NULL,
        error_message VARCHAR2(4000),
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      )`
    );

    await createObjectIfMissing(
      connection,
      `CREATE TABLE document_chunks (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        document_id NUMBER NOT NULL,
        chunk_index NUMBER NOT NULL,
        chunk_text CLOB NOT NULL,
        embedding VECTOR(${config.rag.embeddingDimension}, FLOAT32) NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_document_chunks_document
          FOREIGN KEY (document_id)
          REFERENCES documents(id)
          ON DELETE CASCADE,
        CONSTRAINT uq_document_chunks UNIQUE (document_id, chunk_index)
      )`
    );

    await createObjectIfMissing(
      connection,
      'CREATE INDEX idx_document_chunks_document ON document_chunks (document_id)'
    );

    await createObjectIfMissing(
      connection,
      `CREATE TABLE templates (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        original_name VARCHAR2(1024) NOT NULL,
        stored_name VARCHAR2(1024) NOT NULL,
        storage_path VARCHAR2(2048) NOT NULL,
        mime_type VARCHAR2(255),
        file_size NUMBER,
        template_text CLOB NOT NULL,
        rules_json CLOB NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
      )`
    );

    await createObjectIfMissing(
      connection,
      `CREATE TABLE validation_results (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        template_id NUMBER NOT NULL,
        document_name VARCHAR2(1024) NOT NULL,
        result_json CLOB NOT NULL,
        created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT fk_validation_results_template
          FOREIGN KEY (template_id)
          REFERENCES templates(id)
          ON DELETE CASCADE
      )`
    );

    await createObjectIfMissing(
      connection,
      'CREATE INDEX idx_validation_results_template ON validation_results (template_id)'
    );
  });
}

export async function initializeOracle() {
  if (poolInitialized) {
    return;
  }

  await oracledb.createPool({
    user: config.oracle.user,
    password: config.oracle.password,
    connectString: config.oracle.connectString,
    poolMin: config.oracle.poolMin,
    poolMax: config.oracle.poolMax,
    poolIncrement: config.oracle.poolIncrement
  });

  poolInitialized = true;
  await ensureSchema();
}

export async function closeOracle() {
  if (!poolInitialized) {
    return;
  }

  const pool = oracledb.getPool();
  await pool.close(0);
  poolInitialized = false;
}

export async function createDocument(file) {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `INSERT INTO documents (
        original_name,
        stored_name,
        storage_path,
        mime_type,
        file_size,
        status
      ) VALUES (
        :original_name,
        :stored_name,
        :storage_path,
        :mime_type,
        :file_size,
        'processing'
      ) RETURNING id INTO :id`,
      {
        original_name: file.originalName,
        stored_name: file.storedName,
        storage_path: file.storagePath,
        mime_type: file.mimeType,
        file_size: file.fileSize,
        id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
      }
    );

    await connection.commit();
    return result.outBinds.id[0];
  });
}

export async function updateDocumentStatus(documentId, status, options = {}) {
  const { chunkCount = null, errorMessage = null } = options;

  await withConnection(async (connection) => {
    const assignments = ['status = :status', 'error_message = :error_message'];
    const binds = {
      status,
      error_message: {
        val: errorMessage,
        type: oracledb.STRING,
        maxSize: 4000
      },
      id: {
        val: documentId,
        type: oracledb.NUMBER
      }
    };

    if (chunkCount !== null) {
      assignments.push('chunk_count = :chunk_count');
      binds.chunk_count = {
        val: chunkCount,
        type: oracledb.NUMBER
      };
    }

    await connection.execute(
      `UPDATE documents
         SET ${assignments.join(', ')}
       WHERE id = :id`,
      binds
    );

    await connection.commit();
  });
}

export async function insertDocumentChunks(documentId, chunks) {
  await withConnection(async (connection) => {
    for (const chunk of chunks) {
      await connection.execute(
        `INSERT INTO document_chunks (
          document_id,
          chunk_index,
          chunk_text,
          embedding
        ) VALUES (
          :document_id,
          :chunk_index,
          :chunk_text,
          TO_VECTOR(:embedding_json)
        )`,
        {
          document_id: documentId,
          chunk_index: chunk.index,
          chunk_text: chunk.text,
          embedding_json: toClobBind(toVectorJson(chunk.embedding))
        }
      );
    }

    await connection.commit();
  });
}

export async function listDocuments() {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `SELECT
         id,
         original_name,
         stored_name,
         storage_path,
         mime_type,
         file_size,
         status,
         chunk_count,
         error_message,
         created_at
       FROM documents
       ORDER BY created_at DESC`
    );

    return result.rows;
  });
}

export async function searchSimilarChunks(queryEmbedding, topK) {
  const safeTopK = Math.max(1, Math.min(Number(topK) || config.rag.topK, 20));

  return withConnection(async (connection) => {
    const result = await connection.execute(
      `SELECT
         dc.id,
         dc.document_id,
         dc.chunk_index,
         dc.chunk_text,
         d.original_name,
         d.storage_path,
         VECTOR_DISTANCE(dc.embedding, TO_VECTOR(:embedding_json), COSINE) AS distance
       FROM document_chunks dc
       JOIN documents d ON d.id = dc.document_id
      WHERE d.status = 'ready'
      ORDER BY distance ASC
      FETCH FIRST ${safeTopK} ROWS ONLY`,
      {
        embedding_json: toClobBind(toVectorJson(queryEmbedding))
      }
    );

    return result.rows.map((row) => ({
      id: row.ID,
      documentId: row.DOCUMENT_ID,
      chunkIndex: row.CHUNK_INDEX,
      text: row.CHUNK_TEXT,
      originalName: row.ORIGINAL_NAME,
      storagePath: row.STORAGE_PATH,
      distance: row.DISTANCE,
      score: typeof row.DISTANCE === 'number' ? Math.max(0, 1 - row.DISTANCE) : null
    }));
  });
}

export async function createTemplate(template) {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `INSERT INTO templates (
        original_name,
        stored_name,
        storage_path,
        mime_type,
        file_size,
        template_text,
        rules_json
      ) VALUES (
        :original_name,
        :stored_name,
        :storage_path,
        :mime_type,
        :file_size,
        :template_text,
        :rules_json
      ) RETURNING id INTO :id`,
      {
        original_name: template.originalName,
        stored_name: template.storedName,
        storage_path: template.storagePath,
        mime_type: template.mimeType,
        file_size: template.fileSize,
        template_text: toClobBind(template.templateText),
        rules_json: toClobBind(template.rulesJson),
        id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
      }
    );

    await connection.commit();
    return result.outBinds.id[0];
  });
}

export async function listTemplates() {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `SELECT
         id,
         original_name,
         stored_name,
         storage_path,
         mime_type,
         file_size,
         rules_json,
         created_at
       FROM templates
       ORDER BY created_at DESC`
    );

    return result.rows;
  });
}

export async function getTemplate(templateId) {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `SELECT
         id,
         original_name,
         stored_name,
         storage_path,
         mime_type,
         file_size,
         template_text,
         rules_json,
         created_at
       FROM templates
       WHERE id = :id`,
      {
        id: {
          val: Number(templateId),
          type: oracledb.NUMBER
        }
      }
    );

    return result.rows[0] || null;
  });
}

export async function createValidationResult(validationResult) {
  return withConnection(async (connection) => {
    const result = await connection.execute(
      `INSERT INTO validation_results (
        template_id,
        document_name,
        result_json
      ) VALUES (
        :template_id,
        :document_name,
        :result_json
      ) RETURNING id INTO :id`,
      {
        template_id: {
          val: Number(validationResult.templateId),
          type: oracledb.NUMBER
        },
        document_name: validationResult.documentName,
        result_json: toClobBind(validationResult.resultJson),
        id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
      }
    );

    await connection.commit();
    return result.outBinds.id[0];
  });
}
